//! # Passkeys Registry
//!
//! An open on-chain registry mapping WebAuthn credential ids (`rawId`) to
//! the public keys extracted at credential creation.
//!
//! ## Why
//!
//! WebAuthn exposes a credential's public key exactly once — at
//! `navigator.credentials.create()`. A later `credentials.get()` (sign-in on
//! a new device with a synced passkey) returns only `rawId` + assertion.
//! For passkey-controlled NEAR wallet contracts, the public key IS the
//! identity (deterministic NEP-616 account ids are derived from it), so a
//! `rawId -> publicKey` lookup is required to recover the account.
//!
//! ## Trust model
//!
//! Registration is **open by design**: anyone can attach any public key to
//! any `rawId` (writes happen via a function-call access key restricted to
//! [`register`](PasskeysRegistry::register), whose private key ships inside
//! the public passkey executor). The registry is a phonebook, not an
//! authority:
//!
//! * a wrong mapping can never forge anything — clients verify the WebAuthn
//!   assertion signature against each candidate key, and only the true key
//!   verifies;
//! * [`get`](PasskeysRegistry::get) returns ALL registered candidates
//!   (capped) for exactly this reason;
//! * the worst outcome of abuse is storage-staking drain of the contract
//!   balance and cap-filling a `rawId` before its real key is registered —
//!   which requires knowing the victim's high-entropy (>= 100 bits) `rawId`
//!   in advance.

use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use near_sdk::{env, near, store::LookupMap};

/// WebAuthn spec: credential ids generated by authenticators MUST contain
/// at least 100 bits of entropy, which in practice means >= 16 bytes.
const MIN_RAW_ID_LEN: usize = 16;
/// WebAuthn spec: credential ids MUST NOT exceed 1023 bytes.
const MAX_RAW_ID_LEN: usize = 1023;

/// Bounds griefing: an attacker cap-filling a `rawId` must be able to guess
/// it first, while honest re-registrations are idempotent and never grow
/// the list.
const MAX_KEYS_PER_RAW_ID: usize = 8;

/// A validated passkey public key, stored compactly.
#[near(serializers = [borsh])]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PublicKey {
    /// COSE ES256 (-7): P-256, SEC-1 compressed (33 bytes).
    P256([u8; 33]),
    /// COSE EdDSA (-8): Ed25519 (32 bytes).
    Ed25519([u8; 32]),
}

impl PublicKey {
    /// Parse from the curve-prefixed string convention used by the wallet
    /// contracts: `p256:<base58(33 bytes)>` or `ed25519:<base58(32 bytes)>`.
    fn parse(s: &str) -> Option<Self> {
        if let Some(data) = s.strip_prefix("p256:") {
            let bytes: [u8; 33] = bs58::decode(data).into_vec().ok()?.try_into().ok()?;
            // SEC-1 compressed point tag
            matches!(bytes[0], 0x02 | 0x03).then_some(Self::P256(bytes))
        } else if let Some(data) = s.strip_prefix("ed25519:") {
            let bytes: [u8; 32] = bs58::decode(data).into_vec().ok()?.try_into().ok()?;
            Some(Self::Ed25519(bytes))
        } else {
            None
        }
    }

    /// Canonical curve-prefixed string representation.
    fn to_string(&self) -> String {
        match self {
            Self::P256(bytes) => format!("p256:{}", bs58::encode(bytes).into_string()),
            Self::Ed25519(bytes) => format!("ed25519:{}", bs58::encode(bytes).into_string()),
        }
    }
}

#[near(contract_state)]
pub struct PasskeysRegistry {
    keys: LookupMap<Vec<u8>, Vec<PublicKey>>,
}

impl Default for PasskeysRegistry {
    fn default() -> Self {
        Self {
            keys: LookupMap::new(b"k".to_vec()),
        }
    }
}

#[near]
impl PasskeysRegistry {
    /// Register a `rawId -> publicKey` mapping.
    ///
    /// * `passkey_raw_id`: base64url-encoded (unpadded) WebAuthn credential
    ///   id, 16..=1023 bytes decoded.
    /// * `passkey_public_key`: `p256:<base58(SEC-1 compressed, 33 bytes)>`
    ///   or `ed25519:<base58(32 bytes)>`.
    ///
    /// Idempotent: registering an existing pair is a no-op. Panics on
    /// malformed input or when the per-`rawId` cap is reached.
    pub fn register(&mut self, passkey_raw_id: String, passkey_public_key: String) {
        let raw_id = decode_raw_id(&passkey_raw_id);

        let public_key = PublicKey::parse(&passkey_public_key).unwrap_or_else(|| {
            env::panic_str(
                "passkey_public_key must be 'p256:<base58(33 bytes, SEC-1 compressed)>' \
                 or 'ed25519:<base58(32 bytes)>'",
            )
        });

        let keys = self.keys.entry(raw_id).or_default();

        if keys.contains(&public_key) {
            // idempotent no-op
            return;
        }

        assert!(
            keys.len() < MAX_KEYS_PER_RAW_ID,
            "too many public keys registered for this rawId",
        );

        keys.push(public_key);

        env::log_str(&format!(
            r#"EVENT_JSON:{{"standard":"passkeys-registry","version":"1.0.0","event":"register","data":[{{"raw_id":{},"public_key":{}}}]}}"#,
            near_sdk::serde_json::to_string(&passkey_raw_id).unwrap_or_else(|_| unreachable!()),
            near_sdk::serde_json::to_string(&passkey_public_key)
                .unwrap_or_else(|_| unreachable!()),
        ));
    }

    /// Returns all public keys ever registered for the given
    /// base64url-encoded (unpadded) `rawId`, in registration order.
    ///
    /// Returns an empty list for unknown `rawId`s. Callers MUST disambiguate
    /// the candidates by verifying their WebAuthn assertion signature
    /// against each of them — only the credential's true key verifies.
    pub fn get(&self, passkey_raw_id: String) -> Vec<String> {
        self.keys
            .get(&decode_raw_id(&passkey_raw_id))
            .map(|keys| keys.iter().map(PublicKey::to_string).collect())
            .unwrap_or_default()
    }
}

fn decode_raw_id(raw_id: &str) -> Vec<u8> {
    let decoded = URL_SAFE_NO_PAD
        .decode(raw_id)
        .unwrap_or_else(|_| env::panic_str("passkey_raw_id must be base64url without padding"));

    assert!(
        (MIN_RAW_ID_LEN..=MAX_RAW_ID_LEN).contains(&decoded.len()),
        "passkey_raw_id must be {MIN_RAW_ID_LEN}..={MAX_RAW_ID_LEN} bytes",
    );

    decoded
}

#[cfg(test)]
mod tests {
    use super::*;

    fn raw_id(bytes: &[u8]) -> String {
        URL_SAFE_NO_PAD.encode(bytes)
    }

    const P256_KEY: &str = "p256:tKC1x8Zbnq4wsBHZ2nMFNRJZa7pn6T3jrDp6DBjKvcJx";
    const ED25519_KEY: &str = "ed25519:6E8sCci9badyRkXb3JoRpBj5p8C6Tw41ELDZoiihKEtp";

    fn p256_key() -> String {
        format!(
            "p256:{}",
            bs58::encode(
                [0x02].iter().chain([7u8; 32].iter()).copied().collect::<Vec<u8>>()
            )
            .into_string()
        )
    }

    #[test]
    fn register_get_roundtrip() {
        let mut contract = PasskeysRegistry::default();
        let id = raw_id(&[1u8; 16]);

        assert!(contract.get(id.clone()).is_empty());

        contract.register(id.clone(), p256_key());
        assert_eq!(contract.get(id.clone()), vec![p256_key()]);

        // idempotent
        contract.register(id.clone(), p256_key());
        assert_eq!(contract.get(id.clone()), vec![p256_key()]);

        // second key preserves order
        contract.register(id.clone(), ED25519_KEY.to_string());
        assert_eq!(contract.get(id), vec![p256_key(), ED25519_KEY.to_string()]);
    }

    #[test]
    fn cap_per_raw_id() {
        let mut contract = PasskeysRegistry::default();
        let id = raw_id(&[2u8; 16]);

        for i in 0..MAX_KEYS_PER_RAW_ID {
            let mut bytes = [7u8; 32];
            bytes[0] = u8::try_from(i).unwrap();
            contract.register(
                id.clone(),
                format!("ed25519:{}", bs58::encode(&bytes).into_string()),
            );
        }

        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            contract.register(id.clone(), p256_key());
        }));
        assert!(result.is_err(), "cap must be enforced");
    }

    #[test]
    fn rejects_malformed() {
        let mut contract = PasskeysRegistry::default();

        for (id, key) in [
            // invalid base64url
            ("not!base64url".to_string(), p256_key()),
            // padded base64
            (
                base64::engine::general_purpose::URL_SAFE.encode([3u8; 16]),
                p256_key(),
            ),
            // too short rawId
            (raw_id(&[3u8; 15]), p256_key()),
            // too long rawId
            (raw_id(&vec![3u8; 1024]), p256_key()),
            // missing curve prefix
            (raw_id(&[3u8; 16]), "6E8sCci9badyRkXb3JoRpBj5p8C6Tw41ELDZoiihKEtp".to_string()),
            // wrong p256 length (32 instead of 33)
            (
                raw_id(&[3u8; 16]),
                format!("p256:{}", bs58::encode([7u8; 32]).into_string()),
            ),
            // wrong SEC-1 tag
            (
                raw_id(&[3u8; 16]),
                format!(
                    "p256:{}",
                    bs58::encode(
                        [0x05].iter().chain([7u8; 32].iter()).copied().collect::<Vec<u8>>()
                    )
                    .into_string()
                ),
            ),
            // wrong ed25519 length
            (
                raw_id(&[3u8; 16]),
                format!("ed25519:{}", bs58::encode([7u8; 31]).into_string()),
            ),
            // unknown curve
            (raw_id(&[3u8; 16]), P256_KEY.replace("p256", "secp256k1")),
        ] {
            let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                contract.register(id.clone(), key.clone());
            }));
            assert!(result.is_err(), "must reject: {id} {key}");
        }
    }
}
